### PR TITLE
Add usb content / shared to www and basic nginx config

### PR DESCRIPTION
**Pull request by kldavis4**

### CODE REVIEW

**Comment by edwinsteele** [comment]
The geerlingguy.nginx role is upstream, and should be configurable completely via variables. The USB mount bit looks good, and I'll have a look at the nginx changes to work out how best to integrate them. Feel free to split out the USB stuff if you want to get it in quickly, otherwise we can work it through in a single PR. Apologies for the slow response - my github notifications were broken.

**Comment by kldavis4** [comment]
Thanks for looking it over. No rush on getting this resolved. I'll see if I can refactor some of the changes to use the upstream nginx configuration and improve this PR. We were in a bit of a rush near the end of the event and I didn't have a lot of time to figure out the cleanest way to do some of the changes.

**Comment by kldavis4** [comment]
Fixed this to not modify the geerlingguy.nginx role. It looks like it is failing the ansible-lint check because of the shell cp commands. I am not sure how best to resolve this, though. 

It is cloning the biblebox-skeleton project and then moving it into place (/var/www/biblebox/biblebox_default & /etc/biblebox). It doesn't look like I can do this with the copy module (with remote_src=true) because recursive copy isn't working (https://github.com/ansible/ansible-modules-core/issues/2875). 

I've also looked into whether the git module could checkout the repository locally. Then I could use the copy module to directly copy files from ansible host to the target directories on the remote. The git module doesn't seem to have an option for local checkout on the host, though. Perhaps checking it out by running the checkout tasks against the ansible host would be an option (http://stackoverflow.com/questions/18900236/run-command-on-the-ansible-host)? 

Another option would be merging the biblebox-skeleton repo into the biblebox-pi repo or set it up as a submodule. Any thoughts on how best to resolve?

**Comment by edwinsteele** [comment]
I think the checkout and copy model is fine at the moment, though submodules are an option too (I'm not really familiar with them, so I can't comment). The [synchronize](https://docs.ansible.com/ansible/synchronize_module.html) module is the idiomatic way to do the copy on a remote machine. That will deal with the ansible-lint problem. From the examples on that page:

```
# Synchronize two directories on one remote host.
synchronize:
    src: /first/absolute/path
    dest: /second/absolute/path
delegate_to: "{{ inventory_hostname }}"
```

The module names are a bit confusing... it took me a while to find synchronize, all the while puzzling why there wasn't anything builtin for doing a simple remote copy!

**Pull request merged**
